[package]
name = "collections"
version = "0.1.0"
edition = "2021"

[dependencies]
async_std = { path = "../../modules/async_std", features = [
    "alloc",
    "irq",
    "multitask",
    "fs",
] }
async_futures-bounded = { path = "../../modules/async_futures-bounded" }
