[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
# multihash = "0.19.3"
# multihash = { path = "../../../ak_multihash_user", package = "ak_multihash_user" }
fastrand = "2.3.0"
