[package]
name = "akm"
version = "0.1.0"
edition = "2021"

[dependencies]
async_std = { path = "../../modules/async_std", features = [
    "irq",
    "multitask"
] }
ak_futures-timer = { path = "../../modules/ak_futures-timer" }
