[package]
name = "user_boot"
version = "0.1.0"
edition = "2021"

[dependencies]
async_std = { path = "../../modules/async_std", features = ["monolithic"] }
trampoline = { path = "../../modules/trampoline" }
